<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4da9aff0ec2e7148740bae027d257091
{
    public static $files = array (
        '98f1e8d9fb5f3d77e1b7e841e9baa661' => __DIR__ . '/..' . '/saml_settings.php',
    );

    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'RobRichards\\XMLSecLibs\\' => 23,
        ),
        'O' => 
        array (
            'OneLogin\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'RobRichards\\XMLSecLibs\\' => 
        array (
            0 => __DIR__ . '/..' . '/robrichards/xmlseclibs/src',
        ),
        'OneLogin\\' => 
        array (
            0 => __DIR__ . '/..' . '/onelogin/php-saml/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4da9aff0ec2e7148740bae027d257091::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4da9aff0ec2e7148740bae027d257091::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
